[project]
name = "agentic-interview"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.1",
    "openai>=1.79.0",
    "openai-agents>=0.0.15",
    "pymongo>=4.13.0",
    "python-dotenv>=1.1.0",
    "tqdm>=4.67.1",
]

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true
