[project]
name = "agentic-interview"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cryptography>=45.0.3",
    "django>=5.2.1",
    "djangorestframework>=3.16.0",
    "djongo>=1.2.31",
    "langchain>=0.3.25",
    "langchain-mongodb>=0.6.2",
    "pyjwt>=2.10.1",
    "pymongo>=4.13.0",
    "python-dotenv>=1.1.0",
]

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true
